# Class: stns_v1::server::config
# ===========================
#
# stns_v1::server::config is to configure stns.

class stns_v1::server::config (
  $port     = $stns_v1::server::port,
  $user     = $stns_v1::server::user,
  $password = $stns_v1::server::password,
){

  concat { '/etc/stns/stns.conf':
    ensure => present,
    owner  => 'root',
    group  => 'root',
    mode   => '0644',
    notify => Class['stns_v1::server::service'],
  }

  concat::fragment {
    'header':
      target  => '/etc/stns/stns.conf',
      content => "# HEADER: Autogenerated by Puppet.\n\n",
      order   => '01';

    'server_config':
      target  => '/etc/stns/stns.conf',
      content => template('stns_v1/stns.conf.erb'),
      order   => '20';

    'users_config':
      target  => '/etc/stns/stns.conf',
      content => "## Users configurations.\n",
      order   => '40';

    'groups_config':
      target  => '/etc/stns/stns.conf',
      content => "## Groups configurations.\n",
      order   => '60';
  }

}
